# coredns-service-udp.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: coredns
  name: coredns-udp
  namespace: externaldns
spec:
  type: LoadBalancer
  externalIPs:
  - {externalIP}
  ports:
  - name: dns
    port: 53
    protocol: UDP
  selector:
    k8s-app: coredns
